// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

var targets: [Target] = [
    .executableTarget(
        name: "AppModule",
        path: ".",
        swiftSettings: [
            .enableUpcomingFeature("BareSlashRegexLiterals")
        ]
    )
]

#if !SwiftPlaygrounds && !canImport(PlaygroundSupport)
targets.append(
    .testTarget(
        name: "StemistShellUITests",
        dependencies: ["AppModule"],
        path: "Tests/StemistShellUITests"
    )
)
#endif

let package = Package(
    name: "Stemist",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Stemist",
            targets: ["AppModule"],
            bundleIdentifier: "com.ieltsist.stemist",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calendar),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(
                    purposeString: "Use the microphone for IELTS speaking practice and voice feedback."
                ),
                .camera(
                    purposeString: "Use the camera to capture handwritten STEM work for marking."
                ),
                .photoLibrary(
                    purposeString: "Choose handwritten work and source files from your photo library."
                )
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: targets
)
